# Generated by Django 5.0.1 on 2024-08-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InteractionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mouse_movements', models.JSONField()),
                ('click_intervals', models.JSONField()),
                ('keypress_intervals', models.JSONField()),
                ('scroll_positions', models.JSONField(default=list)),
                ('idle_times', models.JSONField(default=list)),
                ('color_depth', models.CharField(max_length=10)),
                ('os', models.CharField(max_length=20)),
                ('browser', models.CharField(max_length=20)),
                ('screen_resolution', models.CharField(max_length=20)),
                ('installed_plugins', models.JSONField(default=list)),
                ('installed_extensions', models.JSONField(default=list)),
                ('browser_rendering_engine', models.CharField(max_length=50)),
                ('client', models.CharField(max_length=5)),
                ('ip_address', models.GenericIPAddressField()),
            ],
            options={
                'verbose_name': 'Interaction Data',
                'verbose_name_plural': 'Interaction Data',
            },
        ),
    ]
